//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetReciclaWebServiceFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesCompra
    {
        public int iddetallecompra { get; set; }
        public Nullable<int> idchatarra { get; set; }
        public Nullable<int> idticketcompra { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<double> subtotal { get; set; }
    
        public virtual Chatarra Chatarra { get; set; }
        public virtual TicketCompra TicketCompra { get; set; }
    }
}
