//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetReciclaWebServiceFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesVenta
    {
        public int iddetallesventa { get; set; }
        public Nullable<int> idprecioventa { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<int> subtotal { get; set; }
        public Nullable<int> idticketventa { get; set; }
    
        public virtual PrecioVenta PrecioVenta { get; set; }
        public virtual TicketVenta TicketVenta { get; set; }
    }
}
