//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetReciclaWebServiceFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetreciclawebfinalEntities : DbContext
    {
        public MetreciclawebfinalEntities()
            : base("name=MetreciclawebfinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Chatarra> Chatarra { get; set; }
        public virtual DbSet<DetallesCompra> DetallesCompra { get; set; }
        public virtual DbSet<DetallesVenta> DetallesVenta { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Gastos> Gastos { get; set; }
        public virtual DbSet<LocalVenta> LocalVenta { get; set; }
        public virtual DbSet<PrecioVenta> PrecioVenta { get; set; }
        public virtual DbSet<TicketCompra> TicketCompra { get; set; }
        public virtual DbSet<TicketVenta> TicketVenta { get; set; }
        public virtual DbSet<TotalCompra> TotalCompra { get; set; }
        public virtual DbSet<TotalVenta> TotalVenta { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vendedores> Vendedores { get; set; }
    }
}
