//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetReciclaWebServiceFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrecioVenta()
        {
            this.DetallesVenta = new HashSet<DetallesVenta>();
        }
    
        public int idprecioventa { get; set; }
        public Nullable<int> idchatarra { get; set; }
        public Nullable<int> idlocalventa { get; set; }
        public Nullable<int> precioventa1 { get; set; }
    
        public virtual Chatarra Chatarra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesVenta> DetallesVenta { get; set; }
        public virtual LocalVenta LocalVenta { get; set; }
    }
}
