//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetReciclaWebServiceFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketCompra()
        {
            this.DetallesCompra = new HashSet<DetallesCompra>();
            this.TotalCompra = new HashSet<TotalCompra>();
        }
    
        public int idticketcompra { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idvendedor { get; set; }
        public Nullable<int> idusuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesCompra> DetallesCompra { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Vendedores Vendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalCompra> TotalCompra { get; set; }
    }
}
